n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('É numérico? ', n.isnumeric())
print('É alfabetico? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está em somente letras maiúsculas? ', n.isupper())
print('Está somente em letras minusculas? ', n.islower())
print('Está capitalizado? ', n.istitle())
print('Só tem espaços? ', n.isspace())
